### ISSUE TITLE
Failing to extend 

### ISSUE THREAD

**Issue by sergelerner** [APIs-guru/graphql-faker#15] opened 2017-07-13 14:21 UTC
First of all - awesome project!

I wish to extend my project graphql api, add additional types, and test the client. Im not sure I understand how extend works here.

First of all I was following the gif animation in the readme, I've extended github api, and I have the following in the schema just like in that gif

```
extend type User {
  petImage: String @fake(type:imageUrl, options: { imageCategory:cats })
}
```

once I try to save, it prompts me with **"Must provide schema definition with query type or a type named Query."**

So I thought to add a Query type

```
extend type User {
  petImage: String @fake(type:imageUrl, options: { imageCategory:cats })
}


type Query {
  user: User
}
```

then it fails to save again and prompts me with **"Type "User" not found in document."**

What am I missing here?

**Comment by IvanGoncharov** [comment] 2017-07-13 17:56
@sergelerner Strange, I can't reproduce this issue.
You don't need to add `type Query` so your first sample is perfectly valid one.

Can you please provide version of graphql-faker package:
```
npm list -g --depth=0 | grep graphql-faker
```
Also please specify CLI command your use to run faker, but don't forget to replace your Authorization token.

Can you please create file `test.graphql` with following content:
```
extend type User {
  petImage: String @fake(type:imageUrl, options: { imageCategory:cats })
}
```
And than run these command with your GitHub token:
```
graphql-faker --extend https://api.github.com/graphql -H "Authorization: bearer <YOUR_TOKEN>" test.graphql
```

**Comment by sergelerner** [comment] 2017-07-13 19:12
@IvanGoncharov thanks! I wish I could say what was it exactly, I followed along and it works! I manage to extend github api : )

Now when I try to extend my own api I get the following error:

```
Error: Invalid or incomplete schema, unknown type: . Ensure that a full introspection query is used in order to build a client schema.
    at getNamedType (/usr/local/lib/node_modules/graphql-faker/node_modules/graphql/utilities/buildClientSchema.js:102:13)
    at getType (/usr/local/lib/node_modules/graphql-faker/node_modules/graphql/utilities/buildClientSchema.js:93:12)
    at getOutputType (/usr/local/lib/node_modules/graphql-faker/node_modules/graphql/utilities/buildClientSchema.js:116:16)
    at /usr/local/lib/node_modules/graphql-faker/node_modules/graphql/utilities/buildClientSchema.js:237:15
    at /usr/local/lib/node_modules/graphql-faker/node_modules/graphql/jsutils/keyValMap.js:36:31
    at Array.reduce (native)
    at keyValMap (/usr/local/lib/node_modules/graphql-faker/node_modules/graphql/jsutils/keyValMap.js:35:15)
    at buildFieldDefMap (/usr/local/lib/node_modules/graphql-faker/node_modules/graphql/utilities/buildClientSchema.js:231:36)
    at fields (/usr/local/lib/node_modules/graphql-faker/node_modules/graphql/utilities/buildClientSchema.js:180:16)
    at resolveThunk (/usr/local/lib/node_modules/graphql-faker/node_modules/graphql/type/definition.js:161:40)
```

I know its about my api, but any chance you are familiar with that error message?

**Comment by IvanGoncharov** [comment] 2017-07-13 20:01
@sergelerner Can you please attach results of this query:
https://github.com/graphql/graphql-js/blob/d7fe6613af5ecb2c90f367425c8faa74474dc69f/src/utilities/introspectionQuery.js#L15-L105

Your exception is thrown here: https://github.com/graphql/graphql-js/blob/d7fe6613af5ecb2c90f367425c8faa74474dc69f/src/utilities/buildClientSchema.js#L149
And `unknown type: .` looks interesting, since it mean you have empty string intead of type name somewhere inside introspection result. I would suggest to search for `""` pattern in JSON responce.
What GraphQL library you use on backend?

**Comment by sergelerner** [comment] 2017-07-16 06:51
@IvanGoncharov 
thanks once gain with the directions! 
from introspecting I found we have bunch of `name: null` which might be cause... 
didnt find any empty strings tho.

here is sample from running that introspectionQuery you shared,

```
   {
              "args": [],
              "deprecationReason": "",
              "description": "",
              "isDeprecated": false,
              "name": "list",
              "type": {
                "kind": "LIST",
                **"name": null,**
                "ofType": {
                  "kind": "OBJECT",
                  "name": "company",
                  "ofType": null
                }
              }
            }
          ],
          "inputFields": null,
          "interfaces": [],
          "kind": "OBJECT",
          "name": "companies",
          "possibleTypes": null
        },
        {
          "description": "",
          "enumValues": null,
          "fields": [
            {
              "args": [],
              "deprecationReason": "",
              "description": "",
              "isDeprecated": false,
              "name": "list",
              "type": {
                "kind": "LIST",
                **"name": null,**
                "ofType": {
                  "kind": "OBJECT",
                  "name": "experience",
                  "ofType": null
                }
              }
            }
```

thing is that many of those null we dont recognize of where they come from, so it could be the graphql framework we use... which is btw [graphql-go](https://github.com/graphql-go/graphql)

**Comment by IvanGoncharov** [comment] 2017-07-17 08:11
@sergelerner You can try to simplify your introspection result by removing additional types.

Can I close this issue?

**Comment by sergelerner** [comment] 2017-07-17 18:22
@IvanGoncharov Yes, thank you! : )

**Closed** 2017-07-17 19:47 UTC
