### ISSUE TITLE
extending amount of results returned on fake response

### ISSUE THREAD

**Issue by idkjs** [APIs-guru/graphql-faker#40] opened 2018-02-21 15:22 UTC
Is it possible pass query variable for 20 results, for example?

**Comment by IvanGoncharov** [comment] 2018-02-21 17:00
@idkjs I'm confused. Can you please provide more detail description.
Do you want to make arrays bigger or something else?

**Comment by idkjs** [comment] 2018-02-23 20:34
I guess should add and a (count:Int) variable to the Companies query and see what happens. I was just trying to get more than two results back from the default companies query

**Comment by OlzhasAlexandrov** [comment] 2018-02-27 05:11
Duplicate of https://github.com/APIs-guru/graphql-faker/issues/12

**Closed** 2018-02-27 17:57 UTC
